### PR TITLE
Added a second hierarchy and proposed new contents

### PR DESCRIPTION
**Pull request by lnishan**
This is a initial proposed change following #7 #8 .

I haven't changed the inner layout in case you have any concerns for it.

### CODE REVIEW

**Comment by hkirat** [comment]
Can't merge it right now as the some sub-sections are empty.
Eg : fenwick trees
I think it would be better if we restructure the current list and then add new topics
Though I love the new structure..definitely better than the previous one.

**Comment by lnishan** [comment]
Understood. I was thinking this probably still needs discussion (maybe you would like some other items in there or something).

Thanks, glad to hear that.  
I'll work on the PRs for the initial contents soon after.

**Comment by hkirat** [comment]
Yup I'll add a few things myself too.
Thanks for contributing!

**Comment by lnishan** [comment]
:+1:

**Pull request closed without merging**
